title: plug
author: Shantanu Mishra
email: dev@8hantanu.net
description: >
  unleash efficiency!
  a collection of simple bash scripts to accelerate day-to-day tasks or cli-based workflows

url: https://8hantanu.net
baseurl: /plug

remote_theme: yree/mold
footer_content: >
  ##### Â© 2024 [8hantanu](https://8hantanu.net) | ğŸ“¬ [comment](javascript:window.location='mailto:hey@8hantanu.net?subject='+encodeURIComponent(document.title)) | â¬…ï¸ [previous](..)
